Python version 3.9 + pipenv fix +  tiny improvements
variant-inc/actions-python pull request #9
Opened 2022-01-13 10:37 UTC by Dryja

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes [#8](https://usxtech.atlassian.net/browse/CLOUD-8)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

```text
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
```

- [ ] Sanity Testing

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added documentation to test

2022-01-16 18:27 UTC, vibindaniel requested changes

2022-01-26 15:53 UTC, vibindaniel approved these changes

2022-01-26 16:12 UTC, hpatel826 requested changes
@Dryja please update `.github/workflows/lint.yaml` (upgrade to v4 and add VALIDATE_GITHUB_ACTIONS: false)

```
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_DOCKERFILE: false
          VALIDATE_GITHUB_ACTIONS: false
```

2022-01-27 13:22 UTC, hpatel826 approved these changes

2022-01-28 14:11 UTC, hpatel826 approved these changes

2022-01-28 15:45 UTC, merged